version: "3.6"

services:
  datastore-gui:
    image: 346o/datastore-gui:latest
    ports:
      - 8080:8080
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - DATASTORE_EMULATOR_HOST=datastore:8081

  datastore:
    image: ehacke/datastore-emulator:latest
    environment:
      - DATASTORE_PROJECT_ID=${PROJECT_ID}
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081
