version: "3.6"

services:
  datastore-gui:
    image: 346o/datastore-gui:latest
    ports:
      - 3000:3000 # PORT:PORT
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - DATASTORE_EMULATOR_HOST=datastore:8081
      - PORT=3000

  datastore:
    image: ehacke/datastore-emulator:latest
    environment:
      - DATASTORE_PROJECT_ID=${PROJECT_ID}
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081
