name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        make PLATFORM=linux/amd64 docker-build
        make PLATFORM=linux/arm64 docker-build

    - name: Push the Docker Image
      run: |
        make PLATFORM=linux/amd64 docker-push
        make PLATFORM=linux/arm64 docker-push
